# Generated by Django 3.1.7 on 2021-03-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_advuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='contacts',
            field=models.CharField(max_length=40, verbose_name='Телефон'),
        ),
    ]
