# Generated by Django 3.1.7 on 2021-03-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210319_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='bb',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Улица или проспект'),
        ),
    ]
