# Generated by Django 3.1.7 on 2021-03-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.delivery', verbose_name='Службы доставки'),
        ),
    ]
