# Generated by Django 3.1.7 on 2021-03-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bb_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='delivery',
        ),
    ]
