# Generated by Django 3.1.7 on 2021-03-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_bb_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='bb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bb', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Служба доставки'),
        ),
    ]
