# Generated by Django 3.1.7 on 2021-03-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210324_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='bb',
        ),
        migrations.AddField(
            model_name='delivery',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Товар'),
        ),
    ]
