# Generated by Django 3.1.7 on 2021-03-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210324_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
