# Generated by Django 3.1.7 on 2021-03-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='comment1',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='bb',
            name='comment2',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='bb',
            name='comment3',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='bb',
            name='Доставка Justin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bb',
            name='Новая почта',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bb',
            name='Укр почта',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
