# Generated by Django 3.1.7 on 2021-03-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210324_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='comment1',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='comment2',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='comment3',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='Доставка Justin',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='Новая почта',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='Укр почта',
        ),
    ]
