# Generated by Django 3.1.7 on 2021-03-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_bb_delivery1'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='comment1',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='bb',
            name='comment2',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='bb',
            name='comment3',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='bb',
            name='delivery2',
            field=models.BooleanField(default=False, verbose_name='Укр почта'),
        ),
        migrations.AddField(
            model_name='bb',
            name='delivery3',
            field=models.BooleanField(default=False, verbose_name='Доставка Justin'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='delivery1',
            field=models.BooleanField(default=False, verbose_name='Новая почта'),
        ),
    ]
