# Generated by Django 3.1.7 on 2021-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210324_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Публиковать'),
        ),
    ]
