# Generated by Django 3.1.7 on 2021-03-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210325_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='invoce',
            field=models.BooleanField(default=False, verbose_name='Оплата по счету'),
        ),
    ]
