# Generated by Django 3.1.7 on 2021-03-30 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210330_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stars', verbose_name='звезда'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='stars',
            name='star',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Звезда'),
        ),
    ]
